GET http://localhost:8080/employee/add?firstName=foo&lastName=bar2
###
GET http://localhost:8080/employee/remove?firstName=foo&lastName=bar31
###
GET http://localhost:8080/employee/get?firstName=foo&lastName=bar

